server:
  port: 8082

spring:
  kafka:
    consumer:
      group-id: tariff_service
      bootstrap-servers: ${KAFKA_SERVER}
      auto-offset-reset: earliest
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl-auto: validate
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            revision_field_name: revision_id
            revision_type_field_name: revision_type
            do_not_audit_optimistic_locking_field: false

application:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    transport-protocol: smtp
    smtp-auth-enabled: true
    smtp-starttls-enabled: true
    debug-enabled: true

applications:
  url:
    auth: ${AUTH_URL}