KAFKA_BOOTSTRAP_SERVERS: localhost:9092
AUTH_URL: http://localhost:8085/auth

logging:
  level:
    com.neoflex.tariffs.integration.feign: DEBUG

spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false