server:
  port: 8083

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl-auto: validate
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            revision_field_name: revision_id
            revision_type_field_name: revision_type
            do_not_audit_optimistic_locking_field: false

product:
  kafka:
    bootstrap-address: ${KAFKA_BOOTSTRAP_SERVERS}
    install-tariff-topic: install-tariff

applications:
  url:
    auth: ${AUTH_URL}